version: '3.9'

services:
  chroma:
    image: chromadb/chroma
    volumes:
      - ./chroma_data:/chroma/chroma_data
    ports:
      - 8090:8000
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
      - CHROMA_SERVER_HTTP_PORT=8000
      - PERSIST_DIRECTORY=/chroma/chroma_data