model:
  llm:
    model_path: "/root/autodl-tmp/root/autodl-tmp/deepseek14b"
    tensor_parallel_size: 1
    max_tokens: 2048
    temperature: 0.7
    max_concurrent_requests: 10
  
  embedding:
    model_name: "BAAI/bge-large-zh-v1.5"
    model_path: "/root/autodl-tmp/model/bge-large-en-v1.5"  # 添加本地路径
    device: "cuda"
    batch_size: 32
  
  rerank:
    model_name: "BAAI/bge-reranker-large"
    model_path: "/root/autodl-tmp/bge-reranker-large"
    device: "cuda"
    batch_size: 16

vector_store:
  type: "chroma"
  persist_directory: "./database/chroma_db"
  collection_name: "default_collection"
  dim: 1024

chunking:
  chunk_size: 512
  chunk_overlap: 50
  
retrieval:
  top_k: 5
  rerank_top_k: 3
  min_similarity: 0.5