model:
  llm:
    type: "openai"  # 选择LLM类型: "deepseek" 或 "openai"
    # 对于OpenAI API:
    api_base_url: "http://localhost:8000/v1"
    model: "/home/xwh/data/models/QwQ-32B-AWQ"
    max_tokens: 2048
    temperature: 0.7
    # model_path: "/root/autodl-tmp/root/autodl-tmp/deepseek14b"
    # tensor_parallel_size: 1
    # max_tokens: 2048
    # temperature: 0.7
    # max_concurrent_requests: 10
  
  embedding:
    model_name: "jinaai/jina-embeddings-v3"
    model_path: "/home/xwh/data/models/jina-embeddings-v3"  # 添加本地路径
    device: "cuda"
    batch_size: 32
  
  rerank:
    model_name: "BAAI/bge-reranker-v2-m3"
    model_path: "/home/xwh/data/models/bge-reranker-v2-m3"
    device: "cuda"
    batch_size: 16

vector_store:
  type: "chroma"
  host: "localhost"
  port: 8090
  collection_name: "apec_collection"
  dim: 1024

chunking:
  chunk_size: 512
  chunk_overlap: 50
  
retrieval:
  top_k: 5
  rerank_top_k: 3
  min_similarity: 0.5